window.Entity = {
	PhysicsDebug: EntityPhysicsDebug,
	Station: EntityStation,
	Sun: EntitySun,
	Planet: EntityPlanet,
	Asteroid: EntityAsteroid,
	Credits: EntityCredits,
	Player: EntityPlayer,
	Shield: EntityShield,
	Laser: EntityLaser,
	Tracker: EntityTracker,
	BouncerOrb: EntityBouncerOrb,
	BouncerAura: EntityBouncerAura,
	Beam: EntityBeam,
	TeslaBeam: EntityTeslaBeam,
	Missile: EntityMissile,
};